# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: config.proto
# plugin: python-betterproto
# This file has been @generated

from typing import List
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class Field(betterproto.Message):
    field_name: str = betterproto.string_field(1)
    array_length: int = betterproto.uint32_field(2)
    pb_type: str = betterproto.string_field(3)
    pb_index: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class SheetMeta(betterproto.Message):
    category: str = betterproto.string_field(1)
    key: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SheetSchema(betterproto.Message):
    name: str = betterproto.string_field(1)
    meta: "SheetMeta" = betterproto.message_field(2)
    fields: List["Field"] = betterproto.message_field(3)


@dataclass(eq=False, repr=False)
class TableSchema(betterproto.Message):
    name: str = betterproto.string_field(1)
    sheets: List["SheetSchema"] = betterproto.message_field(2)


@dataclass(eq=False, repr=False)
class SheetData(betterproto.Message):
    """单张表结构的数据内容"""

    table: str = betterproto.string_field(1)
    sheet: str = betterproto.string_field(2)
    data: List[bytes] = betterproto.bytes_field(3)


@dataclass(eq=False, repr=False)
class ConfigTables(betterproto.Message):
    version: str = betterproto.string_field(1)
    """版本 x.y.z"""

    header_hash: str = betterproto.string_field(2)
    """结构hash值"""

    schemas: List["TableSchema"] = betterproto.message_field(3)
    """所有表结构"""

    datas: List["SheetData"] = betterproto.message_field(4)
    """所有表数据"""
