# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: sheet.proto
# plugin: python-betterproto
# This file has been @generated
import builtins
from typing import List
from dataclasses import dataclass

import betterproto


@dataclass(eq=False, repr=False)
class AbMatchMatchInfo(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    ab_match_activity_id: int = betterproto.uint32_field(2)
    match_activity_id: int = betterproto.uint32_field(3)
    desktop_id_list: str = betterproto.string_field(4)
    consume_id: int = betterproto.uint32_field(5)
    buy_in_condition: str = betterproto.string_field(6)
    mail_template_id: int = betterproto.uint32_field(7)
    max_match_count: int = betterproto.uint32_field(8)
    reward_id: int = betterproto.uint32_field(9)
    point_id: int = betterproto.uint32_field(10)
    match_level: int = betterproto.uint32_field(11)
    priority: int = betterproto.uint32_field(12)


@dataclass(eq=False, repr=False)
class AbMatchPoint(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    rank: int = betterproto.uint32_field(2)
    desktop_id_list: str = betterproto.string_field(3)
    point: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class AbMatchRewardSeq(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    point_lower: int = betterproto.uint32_field(2)
    point_upper: int = betterproto.uint32_field(3)
    reward: str = betterproto.string_field(4)
    chest_mark: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class AbMatchConsumeSeq(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    match_count: int = betterproto.uint32_field(2)
    item_id: int = betterproto.uint32_field(3)
    item_count: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class AchievementAchievement(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    desc_chs: str = betterproto.string_field(7)
    desc_chs_t: str = betterproto.string_field(8)
    desc_jp: str = betterproto.string_field(9)
    desc_en: str = betterproto.string_field(10)
    desc_kr: str = betterproto.string_field(11)
    rare: int = betterproto.uint32_field(12)
    locked: int = betterproto.uint32_field(13)
    group_id: int = betterproto.uint32_field(14)
    sort: int = betterproto.uint32_field(15)
    segment_id: int = betterproto.uint32_field(16)
    base_task: int = betterproto.uint32_field(17)
    reward: str = betterproto.string_field(18)
    hidden: int = betterproto.uint32_field(19)
    deprecated: int = betterproto.uint32_field(20)


@dataclass(eq=False, repr=False)
class AchievementAchievementGroup(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    img: str = betterproto.string_field(7)
    reward: str = betterproto.string_field(8)
    percentage: int = betterproto.uint32_field(9)
    deprecated: int = betterproto.uint32_field(10)
    sort: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class ActivityActivity(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    type: str = betterproto.string_field(9)
    need_popout: int = betterproto.uint32_field(10)


@dataclass(eq=False, repr=False)
class ActivityTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    day: int = betterproto.uint32_field(3)
    base_task_id: int = betterproto.uint32_field(4)
    reward_id: int = betterproto.uint32_field(5)
    reward_count: int = betterproto.uint32_field(6)
    hidden_reward: str = betterproto.string_field(7)
    limit_id: int = betterproto.uint32_field(8)
    deprecated: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityExchange(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    reward_id: int = betterproto.uint32_field(3)
    reward_count: int = betterproto.uint32_field(4)
    consume_id: int = betterproto.uint32_field(5)
    consume_count: int = betterproto.uint32_field(6)
    exchange_limit: int = betterproto.int32_field(7)
    item_limit_id: int = betterproto.uint32_field(8)
    item_limit_count: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityChestUp(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    chest_id: int = betterproto.uint32_field(2)
    title_str_id: int = betterproto.uint32_field(4)
    str_id: str = betterproto.string_field(5)
    chara_str_id: int = betterproto.uint32_field(6)
    item_str_id: int = betterproto.uint32_field(7)
    img: str = betterproto.string_field(8)
    title_img: str = betterproto.string_field(9)
    typeset: int = betterproto.uint32_field(10)
    up_items_type: int = betterproto.uint32_field(11)
    up_items: List[int] = betterproto.uint32_field(12)


@dataclass(eq=False, repr=False)
class ActivityGameTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    base_task_id: int = betterproto.uint32_field(3)
    reward_id: int = betterproto.uint32_field(4)
    reward_count: int = betterproto.uint32_field(5)
    hidden_reward: str = betterproto.string_field(6)
    limit_id: int = betterproto.uint32_field(7)
    deprecated: int = betterproto.uint32_field(8)


@dataclass(eq=False, repr=False)
class ActivityGamePoint(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    point_id: int = betterproto.uint32_field(3)
    point: int = betterproto.uint32_field(4)
    res_id: int = betterproto.uint32_field(5)
    res_count: int = betterproto.uint32_field(6)
    unlock_day: int = betterproto.int32_field(7)
    node_mark: int = betterproto.uint32_field(8)
    image_mark: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityRank(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    leaderboard_id: int = betterproto.uint32_field(2)
    rank_reward_id: int = betterproto.uint32_field(3)
    require_point: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ActivityRankReward(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    lower_rank_bound: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ActivityFlipTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    base_task_id: int = betterproto.uint32_field(3)
    reward: str = betterproto.string_field(4)
    matrix_x: int = betterproto.uint32_field(5)
    matrix_y: int = betterproto.uint32_field(6)
    is_reward: int = betterproto.uint32_field(7)


@dataclass(eq=False, repr=False)
class ActivityFlipInfo(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    flip_count: int = betterproto.uint32_field(2)
    init_task_list: str = betterproto.string_field(3)
    start_time: str = betterproto.string_field(4)
    end_time: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class ActivityDailySign(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    reward_id: int = betterproto.uint32_field(2)
    reward_count: int = betterproto.uint32_field(3)
    day: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ActivityRichmanInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    map_id: int = betterproto.uint32_field(2)
    map_distance: int = betterproto.uint32_field(3)
    chest_id: int = betterproto.uint32_field(4)
    consume_item_id: int = betterproto.uint32_field(5)
    special_item_id: int = betterproto.uint32_field(6)
    step_bank_save: int = betterproto.uint32_field(7)
    finish_bank_save: int = betterproto.uint32_field(8)
    finish_reward_seq: int = betterproto.uint32_field(9)
    step_exp: int = betterproto.uint32_field(10)
    finish_exp: int = betterproto.uint32_field(11)
    item_worth_pool: int = betterproto.uint32_field(12)
    min_avg_worth: int = betterproto.uint32_field(13)
    max_avg_worth: int = betterproto.uint32_field(14)
    chest_pool_seq: int = betterproto.uint32_field(15)


@dataclass(eq=False, repr=False)
class ActivityRichmanMap(betterproto.Message):
    map_id: int = betterproto.uint32_field(1)
    location: int = betterproto.uint32_field(2)
    pos_x: int = betterproto.uint32_field(3)
    pos_y: int = betterproto.uint32_field(4)
    piece_face: int = betterproto.uint32_field(5)
    type: int = betterproto.uint32_field(6)
    param: int = betterproto.uint32_field(7)
    bonus_type: int = betterproto.uint32_field(8)
    worth: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityRichmanLevel(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    id: int = betterproto.uint32_field(3)
    exp: int = betterproto.uint32_field(4)
    buff: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityRichmanEvent(betterproto.Message):
    event_id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    event_type: int = betterproto.uint32_field(3)
    weight: int = betterproto.uint32_field(4)
    param: List[int] = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityPeriodTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    base_task_id: int = betterproto.uint32_field(3)
    reward: str = betterproto.string_field(4)
    interval: int = betterproto.uint32_field(5)
    progress_limit: int = betterproto.uint32_field(6)
    progress_limit_interval: int = betterproto.uint32_field(7)
    reward_limit_day: int = betterproto.uint32_field(8)
    accessible_days: str = betterproto.string_field(9)
    unlock_day: int = betterproto.uint32_field(10)
    deprecated: int = betterproto.uint32_field(11)
    node_mark: int = betterproto.uint32_field(12)


@dataclass(eq=False, repr=False)
class ActivityRandomTaskPool(betterproto.Message):
    pool_id: int = betterproto.uint32_field(1)
    task_id: int = betterproto.uint32_field(2)
    activity_id: int = betterproto.uint32_field(3)
    base_task_id: int = betterproto.uint32_field(4)
    reward_id: int = betterproto.uint32_field(5)
    reward_count: int = betterproto.uint32_field(6)
    weight: int = betterproto.uint32_field(7)
    hidden_reward: str = betterproto.string_field(8)
    limit_id: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityRandomTaskInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    pool_id: List[int] = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ActivityRichmanRewardSeq(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    count: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ActivityActivityBuff(betterproto.Message):
    buff_id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    buff_level: int = betterproto.uint32_field(3)
    buff_type: int = betterproto.uint32_field(4)
    upgrade_resource_id: int = betterproto.uint32_field(5)
    upgrade_resource_count: int = betterproto.uint32_field(6)
    effect: int = betterproto.uint32_field(7)
    unlock_params: List[int] = betterproto.uint32_field(8)
    effect_desc: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityBuffCondition(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ActivityGamePointInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    filter_id: int = betterproto.uint32_field(2)
    reward_mail_template: int = betterproto.uint32_field(3)
    max_point_limit_day: int = betterproto.int32_field(4)
    should_rank: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityGamePointRank(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    rank_rate_lower: int = betterproto.uint32_field(2)
    rank_rate_upper: int = betterproto.uint32_field(3)
    reward: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ActivityGamePointFilter(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    has_robot: str = betterproto.string_field(2)
    category: str = betterproto.string_field(3)
    room: str = betterproto.string_field(4)
    mode: str = betterproto.string_field(5)
    point_coe: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityActivityRoom(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    sort: int = betterproto.uint32_field(2)
    str_name: str = betterproto.string_field(3)
    str_rule: str = betterproto.string_field(4)
    dora3_mode: int = betterproto.uint32_field(5)
    begin_open_mode: int = betterproto.uint32_field(6)
    muyu_mode: int = betterproto.uint32_field(7)
    xuezhan_mode: int = betterproto.uint32_field(8)
    huanzhang_mode: int = betterproto.uint32_field(9)
    chuanma_mode: int = betterproto.uint32_field(10)
    jiuchao_mode: int = betterproto.uint32_field(11)
    reveal_discard: int = betterproto.uint32_field(12)
    field_spell_mode: int = betterproto.uint32_field(13)
    zhanxing_mode: int = betterproto.uint32_field(14)
    tianming_mode: int = betterproto.uint32_field(15)
    yongchang_mode: int = betterproto.uint32_field(16)
    hunzhiyiji_mode: int = betterproto.uint32_field(17)


@dataclass(eq=False, repr=False)
class ActivitySnsActivity(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    disable: int = betterproto.uint32_field(2)
    pm: int = betterproto.uint32_field(3)
    period: int = betterproto.uint32_field(4)
    activity_id: int = betterproto.uint32_field(5)
    content_str_id: int = betterproto.uint32_field(6)
    parent_id: int = betterproto.uint32_field(7)
    char_id: int = betterproto.uint32_field(8)
    char_str_id: int = betterproto.uint32_field(9)
    reply_char_id: int = betterproto.uint32_field(10)
    reply_char_str_id: int = betterproto.uint32_field(11)
    choice_id: int = betterproto.uint32_field(12)
    like: int = betterproto.uint32_field(13)
    unlock_time: str = betterproto.string_field(14)
    unlock_item_id: int = betterproto.uint32_field(15)
    unlock_item_count: int = betterproto.uint32_field(16)
    content_image: List[str] = betterproto.string_field(17)


@dataclass(eq=False, repr=False)
class ActivityMineActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    reward_group: int = betterproto.uint32_field(2)
    cost_item: str = betterproto.string_field(3)
    map_size_x: int = betterproto.uint32_field(4)
    map_size_y: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityMineReward(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    reward_id: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)
    type: int = betterproto.uint32_field(4)
    x: int = betterproto.uint32_field(5)
    y: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityRpgActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    base_hp: int = betterproto.uint32_field(2)
    base_atk: int = betterproto.uint32_field(3)
    base_dex: int = betterproto.uint32_field(4)
    base_luk: int = betterproto.uint32_field(5)
    ds_atk: int = betterproto.uint32_field(6)
    special_heal: int = betterproto.uint32_field(7)
    chain_atk: List[int] = betterproto.uint32_field(8)
    monster_group: int = betterproto.uint32_field(9)
    sanma_debuff: int = betterproto.uint32_field(10)
    has_robot: int = betterproto.uint32_field(11)
    category: str = betterproto.string_field(12)
    mode: str = betterproto.string_field(13)
    room: str = betterproto.string_field(14)
    daily_limit: int = betterproto.uint32_field(15)


@dataclass(eq=False, repr=False)
class ActivityRpgMonsterGroup(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    seq: int = betterproto.uint32_field(2)
    type: int = betterproto.uint32_field(3)
    hp: int = betterproto.uint32_field(4)
    atk: int = betterproto.uint32_field(5)
    reward: str = betterproto.string_field(6)
    season: int = betterproto.uint32_field(7)
    chapters: str = betterproto.string_field(8)
    imaget_path: str = betterproto.string_field(9)
    background: str = betterproto.string_field(10)
    name_str_id: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class ActivityArenaActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    match_time: str = betterproto.string_field(2)
    ticket_time_limit: str = betterproto.string_field(3)
    ticket_item_id: int = betterproto.uint32_field(4)
    ticket_price: str = betterproto.string_field(5)
    desktop_id: int = betterproto.uint32_field(6)
    max_win_count: int = betterproto.uint32_field(7)
    max_lose_count: int = betterproto.uint32_field(8)
    reward_group: int = betterproto.uint32_field(9)
    daily_ticket_limit: int = betterproto.uint32_field(10)
    mail_template: int = betterproto.uint32_field(11)
    arena_reward_display_group: int = betterproto.uint32_field(12)
    level_limit: int = betterproto.uint32_field(13)


@dataclass(eq=False, repr=False)
class ActivityArenaReward(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    win_count: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class ActivityArenaRewardDisplay(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    win_count_min: int = betterproto.uint32_field(2)
    win_count_max: int = betterproto.uint32_field(3)
    reward_1: int = betterproto.uint32_field(4)
    reward_1_remark: str = betterproto.string_field(5)
    reward_2: int = betterproto.uint32_field(6)
    reward_2_remark: str = betterproto.string_field(7)
    reward_3: int = betterproto.uint32_field(8)
    reward_3_remark: str = betterproto.string_field(9)
    reward_4: int = betterproto.uint32_field(10)
    reward_4_remark: str = betterproto.string_field(11)


@dataclass(eq=False, repr=False)
class ActivitySegmentTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    base_task_id: int = betterproto.uint32_field(3)
    max_finish_count: int = betterproto.uint32_field(4)
    reward: str = betterproto.string_field(5)
    interval: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityFeedActivityInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    max_feed_count: int = betterproto.uint32_field(2)
    feed_reward_id: int = betterproto.uint32_field(3)
    friend_send_limit: int = betterproto.uint32_field(4)
    friend_recv_limit: int = betterproto.uint32_field(5)
    food_item_id: List[int] = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityFeedActivityReward(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    count: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)
    img_stage: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ActivityVoteActivity(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    vote_item: int = betterproto.uint32_field(2)
    choice_id_list: str = betterproto.string_field(3)
    vote_end_time: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ActivityRpgV2Activity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    base_atk: int = betterproto.uint32_field(2)
    monster_group: int = betterproto.uint32_field(3)
    sanma_debuff: int = betterproto.uint32_field(4)
    special_debuff: int = betterproto.uint32_field(5)
    has_robot: int = betterproto.uint32_field(6)
    category: str = betterproto.string_field(7)
    mode: str = betterproto.string_field(8)
    room: str = betterproto.string_field(9)
    daily_limit: int = betterproto.uint32_field(10)
    mail_template_id: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class ActivitySpotActivity(betterproto.Message):
    unique_id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    dep: int = betterproto.uint32_field(3)
    limit_day: int = betterproto.uint32_field(4)
    spot_group: int = betterproto.uint32_field(5)
    unlock_spot_item: str = betterproto.string_field(6)
    content_path: str = betterproto.string_field(7)
    unlock_item: str = betterproto.string_field(8)
    unlock_by_ending_id: int = betterproto.uint32_field(9)
    unlock_ending_id: List[str] = betterproto.string_field(10)
    ending_id: List[int] = betterproto.uint32_field(11)
    ending_id_dep: List[int] = betterproto.uint32_field(12)
    reward: str = betterproto.string_field(13)


@dataclass(eq=False, repr=False)
class ActivityActivityItem(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    item_list: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class ActivityUpgradeActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    mail_id: int = betterproto.uint32_field(2)
    consume_item: str = betterproto.string_field(3)
    total_reward_id: int = betterproto.uint32_field(4)
    reward_id: List[int] = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityUpgradeActivityReward(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    level: int = betterproto.uint32_field(2)
    reward: str = betterproto.string_field(3)
    unlock_day: int = betterproto.uint32_field(4)
    highlight: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityFriendGiftActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    friend_send_limit: int = betterproto.uint32_field(2)
    friend_send_consume: int = betterproto.uint32_field(3)
    friend_recv_limit: int = betterproto.uint32_field(4)
    extra_gift: int = betterproto.uint32_field(5)
    gift_item_id: List[int] = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityUpgradeActivityDisplay(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    level: int = betterproto.uint32_field(2)
    display: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ActivityActivityDesktop(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    desktop_id: int = betterproto.uint32_field(2)
    interval: int = betterproto.uint32_field(3)
    interval_type: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ActivityGachaActivityInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    gacha_pool: int = betterproto.uint32_field(2)
    gacha_control: int = betterproto.uint32_field(3)
    sp_trigger_times: int = betterproto.uint32_field(4)
    sp_rewards: str = betterproto.string_field(5)
    consume: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ActivityGachaPool(betterproto.Message):
    pool_id: int = betterproto.uint32_field(1)
    reward_id: int = betterproto.uint32_field(2)
    count: int = betterproto.uint32_field(3)
    rare: int = betterproto.uint32_field(4)
    item: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class ActivityGachaControl(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ActivityTaskDisplay(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    day: int = betterproto.uint32_field(2)
    task_serial_number: int = betterproto.uint32_field(3)
    task_type: int = betterproto.uint32_field(4)
    period_task_id: int = betterproto.uint32_field(5)
    answer: int = betterproto.uint32_field(6)
    right_str: int = betterproto.uint32_field(7)
    wrong_str: int = betterproto.uint32_field(8)


@dataclass(eq=False, repr=False)
class ActivitySimulationActivityInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    stamina_item_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ActivityRewardMail(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    mail_template_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ActivityCombiningActivityInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    craft_bin: List[int] = betterproto.uint32_field(2)
    craft_bin_price: List[str] = betterproto.string_field(3)
    craft_bin_unlock: List[int] = betterproto.uint32_field(4)
    point_item: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ActivityCombiningCraftPool(betterproto.Message):
    bin_id: int = betterproto.uint32_field(1)
    craft_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ActivityCombiningMap(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    point_item_id: int = betterproto.uint32_field(2)
    point_item_count: int = betterproto.uint32_field(3)
    workbench_count: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ActivityCombiningOrder(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ActivityCombiningCraft(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    group: int = betterproto.uint32_field(3)
    level: int = betterproto.uint32_field(5)
    upgrade_craft_id: int = betterproto.uint32_field(6)
    order_price: str = betterproto.string_field(8)
    if_bonus: int = betterproto.uint32_field(9)
    img_name: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class ActivityChestReplaceUp(betterproto.Message):
    chest_id: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ActivityVillageActivityInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    worker_item_id: int = betterproto.uint32_field(2)
    round_consume: str = betterproto.string_field(3)
    random_building: str = betterproto.string_field(4)
    food_item_id: int = betterproto.uint32_field(5)
    trip_consume: int = betterproto.uint32_field(6)
    trip_cold_down: int = betterproto.uint32_field(7)
    trip_round: int = betterproto.uint32_field(8)
    trip_reward: List[str] = betterproto.string_field(9)
    stage_require: List[str] = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class ActivityVillageBuilding(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    building_id: int = betterproto.uint32_field(2)
    initial: int = betterproto.uint32_field(3)
    building_name: int = betterproto.uint32_field(4)
    level: int = betterproto.uint32_field(5)
    next_level_id: int = betterproto.uint32_field(6)
    produce_item: str = betterproto.string_field(7)
    base_produce: str = betterproto.string_field(8)
    upgrade_item: str = betterproto.string_field(9)
    max_worker_count: int = betterproto.uint32_field(10)
    upgrade_reward: str = betterproto.string_field(11)
    building_stage: int = betterproto.uint32_field(12)
    worker_consume: int = betterproto.uint32_field(13)
    func: str = betterproto.string_field(14)
    args: List[int] = betterproto.uint32_field(15)
    type: int = betterproto.uint32_field(16)


@dataclass(eq=False, repr=False)
class ActivityVillageTask(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    mission_id: int = betterproto.uint32_field(2)
    mission_str: int = betterproto.uint32_field(3)
    fruit_type: str = betterproto.string_field(4)
    consume: str = betterproto.string_field(5)
    reward: str = betterproto.string_field(6)
    unlock_day: int = betterproto.uint32_field(7)
    unlock_point: str = betterproto.string_field(8)
    if_loop: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityLiverEventInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    follower_amount: int = betterproto.uint32_field(2)
    daily_follower_plus: int = betterproto.uint32_field(3)
    intro_text: int = betterproto.uint32_field(4)
    text_max_amount: int = betterproto.uint32_field(5)
    text_create_timer: str = betterproto.string_field(6)
    text_create_weight: str = betterproto.string_field(7)
    rolltext_speed: int = betterproto.uint32_field(8)
    gift_weight: str = betterproto.string_field(9)
    rolltext_gift_time: str = betterproto.string_field(10)
    key_item_id: int = betterproto.uint32_field(11)
    face_time_block: str = betterproto.string_field(12)
    face_weight: str = betterproto.string_field(13)


@dataclass(eq=False, repr=False)
class ActivityLiverTextInfo(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    chara_id: int = betterproto.uint32_field(3)
    mob_str_id: int = betterproto.uint32_field(4)
    normal_text: str = betterproto.string_field(5)
    gift_text: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ActivityFestivalActivity(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    funds_id: int = betterproto.uint32_field(2)
    proposal_id: int = betterproto.uint32_field(3)
    proposal_consume: int = betterproto.uint32_field(4)
    daily_buy_limit: int = betterproto.uint32_field(5)
    arrow_amount: int = betterproto.uint32_field(10)
    max_amount: int = betterproto.uint32_field(11)
    max_proposal_pos: int = betterproto.uint32_field(12)


@dataclass(eq=False, repr=False)
class ActivityFestivalLevel(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    level: int = betterproto.uint32_field(2)
    level_name: int = betterproto.uint32_field(3)
    level_require: str = betterproto.string_field(4)
    level_res: str = betterproto.string_field(5)
    unlock_event_count: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class ActivityFestivalProposal(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    proposal_id: int = betterproto.uint32_field(2)
    unlock_level: int = betterproto.uint32_field(3)
    ending_group: List[int] = betterproto.uint32_field(4)
    client_name: int = betterproto.uint32_field(5)
    client_icon: str = betterproto.string_field(6)
    proposal_text: int = betterproto.uint32_field(7)
    option_text_a: int = betterproto.uint32_field(8)
    option_text_b: int = betterproto.uint32_field(9)


@dataclass(eq=False, repr=False)
class ActivityFestivalEvent(betterproto.Message):
    activity_id: int = betterproto.uint32_field(1)
    event_id: int = betterproto.uint32_field(2)
    position: int = betterproto.uint32_field(3)
    unlock_level: int = betterproto.uint32_field(4)
    ending_group: List[int] = betterproto.uint32_field(5)
    event_title: int = betterproto.uint32_field(6)
    client_name: int = betterproto.uint32_field(7)
    client_icon: str = betterproto.string_field(8)
    event_text: int = betterproto.uint32_field(9)
    option_text_a: int = betterproto.uint32_field(10)
    option_text_b: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class ActivityFestivalEnding(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    ending_id: int = betterproto.uint32_field(2)
    ending_type: int = betterproto.uint32_field(3)
    weight: int = betterproto.uint32_field(4)
    item_plus: str = betterproto.string_field(5)
    item_minus: str = betterproto.string_field(6)
    funds: int = betterproto.int32_field(7)
    ending_text: int = betterproto.uint32_field(8)


@dataclass(eq=False, repr=False)
class AnimationAnimation(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    type: str = betterproto.string_field(3)
    lifetime: int = betterproto.uint32_field(4)
    speed: float = betterproto.float_field(5)
    keypoint: List[int] = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class AudioAudio(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    path: str = betterproto.string_field(2)
    time_length: float = betterproto.float_field(3)
    type: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class AudioBgm(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    auto_hide: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    name_kr: str = betterproto.string_field(7)
    path: str = betterproto.string_field(8)
    time_length: float = betterproto.float_field(9)
    type: str = betterproto.string_field(10)
    unlock_desc_chs: str = betterproto.string_field(11)
    unlock_desc_chs_t: str = betterproto.string_field(12)
    unlock_desc_jp: str = betterproto.string_field(13)
    unlock_desc_en: str = betterproto.string_field(14)
    unlock_desc_kr: str = betterproto.string_field(15)
    unlock_item: int = betterproto.uint32_field(16)


@dataclass(eq=False, repr=False)
class CharacterEmoji(betterproto.Message):
    charid: int = betterproto.uint32_field(1)
    sub_id: int = betterproto.uint32_field(2)
    unlock_desc_chs: str = betterproto.string_field(3)
    unlock_desc_chs_t: str = betterproto.string_field(4)
    unlock_desc_jp: str = betterproto.string_field(5)
    unlock_desc_en: str = betterproto.string_field(6)
    unlock_desc_kr: str = betterproto.string_field(7)
    type: int = betterproto.uint32_field(8)
    view: str = betterproto.string_field(9)
    audio: int = betterproto.uint32_field(10)
    after_unlock_desc_chs: str = betterproto.string_field(11)
    after_unlock_desc_chs_t: str = betterproto.string_field(12)
    after_unlock_desc_jp: str = betterproto.string_field(13)
    after_unlock_desc_en: str = betterproto.string_field(14)
    after_unlock_desc_kr: str = betterproto.string_field(15)
    unlock_type: int = betterproto.uint32_field(16)
    unlock_param: List[int] = betterproto.uint32_field(17)


@dataclass(eq=False, repr=False)
class CharacterCutin(betterproto.Message):
    skinid: int = betterproto.uint32_field(1)
    cutin_name: str = betterproto.string_field(2)
    effect: str = betterproto.string_field(3)
    atlas: str = betterproto.string_field(4)
    char_x: int = betterproto.int32_field(5)
    char_y: int = betterproto.int32_field(6)
    char_width: int = betterproto.uint32_field(7)
    char_height: int = betterproto.uint32_field(8)


@dataclass(eq=False, repr=False)
class CharacterSkin(betterproto.Message):
    skinid: int = betterproto.uint32_field(1)
    spine_layers: int = betterproto.uint32_field(2)
    effects: List[str] = betterproto.string_field(3)
    audio_celebrate: str = betterproto.string_field(4)
    audio_idle: str = betterproto.string_field(5)
    audio_greeting: str = betterproto.string_field(6)
    audio_click: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class ChestChest(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    desc_chs: str = betterproto.string_field(6)
    desc_jp: str = betterproto.string_field(7)
    desc_en: str = betterproto.string_field(8)
    desc_kr: str = betterproto.string_field(9)
    img: str = betterproto.string_field(10)
    gift: int = betterproto.uint32_field(11)
    currency: int = betterproto.uint32_field(12)
    price: int = betterproto.uint32_field(13)
    price10: int = betterproto.uint32_field(14)
    ticket_id: int = betterproto.uint32_field(15)
    ticket_10_id: int = betterproto.uint32_field(16)
    faith_id: int = betterproto.uint32_field(22)
    zone: int = betterproto.uint32_field(23)
    sort: int = betterproto.uint32_field(24)


@dataclass(eq=False, repr=False)
class ChestPool(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChestPoolSeq(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChestItemPool(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChestChestShop(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    chest_id: int = betterproto.uint32_field(2)
    icon: str = betterproto.string_field(3)
    name_chs: str = betterproto.string_field(4)
    name_chs_t: str = betterproto.string_field(5)
    name_jp: str = betterproto.string_field(6)
    name_en: str = betterproto.string_field(7)
    item_id: int = betterproto.uint32_field(8)
    price: int = betterproto.uint32_field(9)
    need_amount: int = betterproto.uint32_field(10)
    check_activity: int = betterproto.uint32_field(11)
    launch_time: str = betterproto.string_field(12)
    remove_limit_mark: int = betterproto.uint32_field(13)
    sort: int = betterproto.uint32_field(14)


@dataclass(eq=False, repr=False)
class ChestPreview(betterproto.Message):
    chest_id: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint32_field(2)
    type: str = betterproto.string_field(3)
    check_activity: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ChestUp(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChestItemPrice(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ChestReplaceUp(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    replace_pool_id: int = betterproto.uint32_field(2)
    count: int = betterproto.uint32_field(3)
    activity_id: int = betterproto.uint32_field(5)
    count_id: int = betterproto.uint32_field(6)
    type: int = betterproto.uint32_field(7)


@dataclass(eq=False, repr=False)
class ChestReplacePool(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    resource_id: int = betterproto.uint32_field(2)
    is_replace: int = betterproto.uint32_field(4)
    add_count: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ComposeCharacompose(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint32_field(2)
    item_num: int = betterproto.uint32_field(3)
    chara_id: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ContestContest(betterproto.Message):
    id: str = betterproto.string_field(1)
    int_value: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class DesktopMatchmode(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    is_open: int = betterproto.uint32_field(2)
    match_group: int = betterproto.uint32_field(3)
    type: int = betterproto.uint32_field(4)
    activity_id: int = betterproto.uint32_field(5)
    open_guyi: int = betterproto.uint32_field(6)
    dora3_mode: int = betterproto.uint32_field(7)
    begin_open_mode: int = betterproto.uint32_field(8)
    muyu_mode: int = betterproto.uint32_field(9)
    xuezhan_mode: int = betterproto.uint32_field(10)
    chuanma_mode: int = betterproto.uint32_field(11)
    huanzhang_mode: int = betterproto.uint32_field(12)
    jiuchao_mode: int = betterproto.uint32_field(13)
    reveal_discard: int = betterproto.uint32_field(14)
    field_spell_mode: int = betterproto.uint32_field(15)
    zhanxing_mode: int = betterproto.uint32_field(16)
    tianming_mode: int = betterproto.uint32_field(17)
    yongchang_mode: int = betterproto.uint32_field(18)
    hunzhiyiji_mode: int = betterproto.uint32_field(19)
    room: int = betterproto.uint32_field(20)
    mode: int = betterproto.uint32_field(21)
    can_sumup: int = betterproto.uint32_field(22)
    room_name_chs: str = betterproto.string_field(23)
    room_name_chs_t: str = betterproto.string_field(24)
    room_name_jp: str = betterproto.string_field(25)
    room_name_en: str = betterproto.string_field(26)
    room_name_kr: str = betterproto.string_field(27)
    glimit_floor: int = betterproto.int32_field(28)
    glimit_ceil: int = betterproto.int32_field(29)
    gcarry: int = betterproto.int32_field(30)
    exchange_rate: int = betterproto.int32_field(31)
    levelpoint1: int = betterproto.int32_field(32)
    levelpoint2: int = betterproto.int32_field(33)
    levelpoint3: int = betterproto.int32_field(34)
    levelpoint4: int = betterproto.int32_field(35)
    fish_point: int = betterproto.int32_field(36)
    init_point: int = betterproto.int32_field(37)
    back_point: int = betterproto.int32_field(38)
    count_point: int = betterproto.int32_field(39)
    buchang: List[int] = betterproto.int32_field(40)
    level_limit: int = betterproto.uint32_field(41)
    level_limit_ceil: int = betterproto.uint32_field(42)
    tip: int = betterproto.int32_field(43)
    friendship: int = betterproto.int32_field(44)
    chest_id: int = betterproto.uint32_field(45)
    chest_exp_add: List[int] = betterproto.uint32_field(46)
    level_match: int = betterproto.uint32_field(47)
    level_match_range: int = betterproto.uint32_field(48)
    level_match_max: int = betterproto.uint32_field(49)


@dataclass(eq=False, repr=False)
class DesktopChest(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    exp_step: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    name_kr: str = betterproto.string_field(7)
    icon: str = betterproto.string_field(8)
    reward_pool: int = betterproto.uint32_field(9)
    select_count: int = betterproto.uint32_field(10)
    repeated: int = betterproto.uint32_field(11)


@dataclass(eq=False, repr=False)
class DesktopSettings(betterproto.Message):
    key: str = betterproto.string_field(1)
    int_value: int = betterproto.int32_field(2)


@dataclass(eq=False, repr=False)
class DesktopFieldSpell(betterproto.Message):
    field: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)
    cardname: str = betterproto.string_field(4)
    sord_card_id: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class EventsSoscoin(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    level_limit: int = betterproto.uint32_field(2)
    level3_limit: int = betterproto.uint32_field(3)
    gold_limit: int = betterproto.uint32_field(4)
    gold_num: int = betterproto.uint32_field(5)
    desc_chs: str = betterproto.string_field(6)
    desc_chs_t: str = betterproto.string_field(7)
    desc_jp: str = betterproto.string_field(8)
    desc_en: str = betterproto.string_field(9)
    desc_kr: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class EventsDailyevent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    reward_type: int = betterproto.uint32_field(2)
    reward_num: int = betterproto.uint32_field(3)
    desc_chs: str = betterproto.string_field(4)
    desc_chs_t: str = betterproto.string_field(5)
    desc_jp: str = betterproto.string_field(6)
    desc_en: str = betterproto.string_field(7)
    desc_kr: str = betterproto.string_field(8)
    active_type: int = betterproto.uint32_field(9)
    type: int = betterproto.uint32_field(11)
    target: int = betterproto.uint32_field(12)
    param: List[str] = betterproto.string_field(13)
    level_limit: str = betterproto.string_field(14)


@dataclass(eq=False, repr=False)
class EventsBaseTask(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    desc_chs: str = betterproto.string_field(2)
    desc_chs_t: str = betterproto.string_field(3)
    desc_jp: str = betterproto.string_field(4)
    desc_en: str = betterproto.string_field(5)
    desc_kr: str = betterproto.string_field(6)
    type: int = betterproto.uint32_field(7)
    target: int = betterproto.uint32_field(8)
    param: List[str] = betterproto.string_field(9)


@dataclass(eq=False, repr=False)
class ExchangeExchange(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    source_currency: int = betterproto.uint32_field(2)
    source_value: int = betterproto.int32_field(3)
    target_currency: int = betterproto.uint32_field(4)
    target_value: int = betterproto.int32_field(5)
    icon: str = betterproto.string_field(6)
    name_chs: str = betterproto.string_field(7)
    name_chs_t: str = betterproto.string_field(8)
    name_jp: str = betterproto.string_field(9)
    name_en: str = betterproto.string_field(10)
    name_kr: str = betterproto.string_field(11)
    desc_chs: str = betterproto.string_field(12)
    desc_chs_t: str = betterproto.string_field(13)
    desc_jp: str = betterproto.string_field(14)
    desc_en: str = betterproto.string_field(15)
    desc_kr: str = betterproto.string_field(16)


@dataclass(eq=False, repr=False)
class ExchangeSearchexchange(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    source_currency: int = betterproto.uint32_field(2)
    source_value: int = betterproto.int32_field(3)
    target_currency: int = betterproto.uint32_field(4)
    target_value: int = betterproto.int32_field(5)
    icon: str = betterproto.string_field(6)
    name_chs: str = betterproto.string_field(7)
    name_chs_t: str = betterproto.string_field(8)
    name_jp: str = betterproto.string_field(9)
    name_en: str = betterproto.string_field(10)
    name_kr: str = betterproto.string_field(11)
    desc_chs: str = betterproto.string_field(12)
    desc_chs_t: str = betterproto.string_field(13)
    desc_jp: str = betterproto.string_field(14)
    desc_en: str = betterproto.string_field(15)
    desc_kor: str = betterproto.string_field(16)


@dataclass(eq=False, repr=False)
class ExchangeFushiquanexchange(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    source_currency: int = betterproto.uint32_field(2)
    source_value: int = betterproto.int32_field(3)
    target_currency: int = betterproto.uint32_field(4)
    target_value: int = betterproto.int32_field(5)
    icon: str = betterproto.string_field(6)
    name_chs: str = betterproto.string_field(7)
    name_chs_t: str = betterproto.string_field(8)
    name_jp: str = betterproto.string_field(9)
    name_en: str = betterproto.string_field(10)
    name_kr: str = betterproto.string_field(11)
    desc_chs: str = betterproto.string_field(12)
    desc_chs_t: str = betterproto.string_field(13)
    desc_jp: str = betterproto.string_field(14)
    desc_en: str = betterproto.string_field(15)
    desc_kr: str = betterproto.string_field(16)


@dataclass(eq=False, repr=False)
class FanFan(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    xuanshang: int = betterproto.uint32_field(7)
    yiman: int = betterproto.uint32_field(8)
    fan_menqing: int = betterproto.uint32_field(9)
    fan_fulu: int = betterproto.uint32_field(10)
    show_index: int = betterproto.uint32_field(11)
    sound: str = betterproto.string_field(12)
    is_guyi: int = betterproto.uint32_field(13)
    rarity: int = betterproto.uint32_field(14)
    show_range_1: int = betterproto.uint32_field(15)
    show_range_2: str = betterproto.string_field(16)
    merge_id: int = betterproto.uint32_field(17)


@dataclass(eq=False, repr=False)
class FandescFandesc(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    tag: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    name_kr: str = betterproto.string_field(7)
    desc_chs: str = betterproto.string_field(8)
    desc_chs_t: str = betterproto.string_field(9)
    desc_jp: str = betterproto.string_field(10)
    desc_en: str = betterproto.string_field(11)
    desc_kr: str = betterproto.string_field(12)
    desc2_chs: str = betterproto.string_field(13)
    desc2_jp: str = betterproto.string_field(14)
    desc2_en: str = betterproto.string_field(15)
    desc2_chs_t: str = betterproto.string_field(16)
    desc2_kr: str = betterproto.string_field(17)
    case: str = betterproto.string_field(18)
    show: int = betterproto.uint32_field(19)
    mode: int = betterproto.uint32_field(20)


@dataclass(eq=False, repr=False)
class GameLiveSelectFilters(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    category: int = betterproto.uint32_field(2)
    mode_id: int = betterproto.uint32_field(3)
    mode: int = betterproto.uint32_field(4)
    tournament_id: int = betterproto.uint32_field(5)
    open: int = betterproto.uint32_field(6)
    initial: int = betterproto.uint32_field(7)
    name1_chs: str = betterproto.string_field(8)
    name1_chs_t: str = betterproto.string_field(9)
    name1_jp: str = betterproto.string_field(10)
    name1_en: str = betterproto.string_field(11)
    name1_kr: str = betterproto.string_field(12)
    name2_chs: str = betterproto.string_field(13)
    name2_chs_t: str = betterproto.string_field(14)
    name2_jp: str = betterproto.string_field(15)
    name2_en: str = betterproto.string_field(16)
    name2_kr: str = betterproto.string_field(17)


@dataclass(eq=False, repr=False)
class InfoError(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    chs: str = betterproto.string_field(2)
    chs_t: str = betterproto.string_field(3)
    jp: str = betterproto.string_field(4)
    en: str = betterproto.string_field(5)
    kr: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class InfoForbidden(betterproto.Message):
    word: str = betterproto.string_field(1)
    type_chs: int = betterproto.uint32_field(2)
    near_chs: int = betterproto.uint32_field(3)
    chs: int = betterproto.uint32_field(4)
    type_us: int = betterproto.uint32_field(5)
    near_us: int = betterproto.uint32_field(6)
    us: int = betterproto.uint32_field(7)
    type_jp: int = betterproto.uint32_field(8)
    near_jp: int = betterproto.uint32_field(9)
    jp: int = betterproto.uint32_field(10)


@dataclass(eq=False, repr=False)
class InfoNear(betterproto.Message):
    word1: str = betterproto.string_field(1)
    word2: str = betterproto.string_field(2)
    word3: str = betterproto.string_field(3)
    word4: str = betterproto.string_field(4)
    word5: str = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class InfoTranslate(betterproto.Message):
    original: str = betterproto.string_field(1)
    chs: str = betterproto.string_field(2)
    chs_t: str = betterproto.string_field(3)
    jp: str = betterproto.string_field(4)
    en: str = betterproto.string_field(5)
    kr: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class ItemDefinitionCurrency(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    desc_chs: str = betterproto.string_field(7)
    desc_chs_t: str = betterproto.string_field(8)
    desc_jp: str = betterproto.string_field(9)
    desc_en: str = betterproto.string_field(10)
    desc_kr: str = betterproto.string_field(11)
    icon: str = betterproto.string_field(12)
    icon_jpg: str = betterproto.string_field(13)


@dataclass(eq=False, repr=False)
class ItemDefinitionItem(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    sort: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_chs_t2: str = betterproto.string_field(5)
    name_jp: str = betterproto.string_field(6)
    name_en: str = betterproto.string_field(7)
    name_kr: str = betterproto.string_field(8)
    desc_func_chs: str = betterproto.string_field(9)
    desc_chs: str = betterproto.string_field(10)
    desc_func_chs_t: str = betterproto.string_field(11)
    desc_chs_t: str = betterproto.string_field(12)
    desc_chs_t2: str = betterproto.string_field(13)
    desc_func_jp: str = betterproto.string_field(14)
    desc_jp: str = betterproto.string_field(15)
    desc_func_en: str = betterproto.string_field(16)
    desc_en: str = betterproto.string_field(17)
    desc_func_kr: str = betterproto.string_field(18)
    desc_kr: str = betterproto.string_field(19)
    icon: str = betterproto.string_field(20)
    icon_transparent: str = betterproto.string_field(21)
    category: int = betterproto.uint32_field(22)
    type: int = betterproto.uint32_field(23)
    is_unique: int = betterproto.uint32_field(24)
    max_stack: int = betterproto.uint32_field(25)
    access: str = betterproto.string_field(26)
    accessinfo: int = betterproto.uint32_field(27)
    func: str = betterproto.string_field(28)
    iargs: List[int] = betterproto.uint32_field(29)
    sargs: List[str] = betterproto.string_field(30)
    can_sell: int = betterproto.uint32_field(31)
    sell_reward_id: int = betterproto.uint32_field(32)
    sell_reward_count: int = betterproto.uint32_field(33)
    item_expire: str = betterproto.string_field(35)
    expire_desc_chs: str = betterproto.string_field(36)
    expire_desc_chs_t: str = betterproto.string_field(37)
    expire_desc_jp: str = betterproto.string_field(38)
    expire_desc_en: str = betterproto.string_field(39)
    expire_desc_kr: str = betterproto.string_field(40)
    region_limit: int = betterproto.uint32_field(41)
    cross_view: int = betterproto.uint32_field(42)
    database_cache: int = betterproto.uint32_field(43)


@dataclass(eq=False, repr=False)
class ItemDefinitionTitle(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    desc_chs: str = betterproto.string_field(7)
    desc_chs_t: str = betterproto.string_field(8)
    desc_jp: str = betterproto.string_field(9)
    desc_en: str = betterproto.string_field(10)
    desc_kr: str = betterproto.string_field(11)
    icon: str = betterproto.string_field(12)
    icon_item: str = betterproto.string_field(13)
    priority: int = betterproto.uint32_field(14)
    unlock_type: int = betterproto.uint32_field(15)
    unlock_param: List[int] = betterproto.uint32_field(16)
    cross_view: int = betterproto.uint32_field(17)


@dataclass(eq=False, repr=False)
class ItemDefinitionCharacter(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    sort: int = betterproto.uint32_field(2)
    launch_time: str = betterproto.string_field(3)
    name_chs: str = betterproto.string_field(4)
    name_chs2: str = betterproto.string_field(5)
    name_chs_t: str = betterproto.string_field(6)
    name_chs_t2: str = betterproto.string_field(7)
    name_jp: str = betterproto.string_field(8)
    name_jp2: str = betterproto.string_field(9)
    name_en: str = betterproto.string_field(10)
    name_kr: str = betterproto.string_field(11)
    open: int = betterproto.uint32_field(12)
    init_skin: int = betterproto.uint32_field(13)
    full_fetter_skin: int = betterproto.uint32_field(14)
    hand: int = betterproto.uint32_field(15)
    favorite: int = betterproto.uint32_field(16)
    star_5_material: str = betterproto.string_field(17)
    star_5_cost: int = betterproto.uint32_field(18)
    can_marry: int = betterproto.uint32_field(19)
    exchange_item_id: int = betterproto.uint32_field(20)
    exchange_item_num: int = betterproto.int32_field(21)
    emo: str = betterproto.string_field(22)
    sound: int = betterproto.uint32_field(23)
    sound_volume: float = betterproto.float_field(24)
    sex: int = betterproto.uint32_field(25)
    desc_stature_chs: str = betterproto.string_field(26)
    desc_stature_chs_t: str = betterproto.string_field(27)
    desc_stature_jp: str = betterproto.string_field(28)
    desc_stature_en: str = betterproto.string_field(29)
    desc_stature_kr: str = betterproto.string_field(30)
    desc_birth_chs: str = betterproto.string_field(31)
    desc_birth_chs_t: str = betterproto.string_field(32)
    desc_birth_jp: str = betterproto.string_field(33)
    desc_birth_en: str = betterproto.string_field(34)
    desc_birth_kr: str = betterproto.string_field(35)
    desc_age_chs: str = betterproto.string_field(36)
    desc_age_chs_t: str = betterproto.string_field(37)
    desc_age_jp: str = betterproto.string_field(38)
    desc_age_en: str = betterproto.string_field(39)
    desc_age_kr: str = betterproto.string_field(40)
    desc_bloodtype_chs: str = betterproto.string_field(41)
    desc_bloodtype_chs_t: str = betterproto.string_field(42)
    desc_bloodtype_jp: str = betterproto.string_field(43)
    desc_bloodtype_en: str = betterproto.string_field(44)
    desc_bloodtype_kr: str = betterproto.string_field(45)
    desc_cv_chs: str = betterproto.string_field(46)
    desc_cv_chs_t: str = betterproto.string_field(47)
    desc_cv_jp: str = betterproto.string_field(48)
    desc_cv_en: str = betterproto.string_field(49)
    desc_cv_kr: str = betterproto.string_field(50)
    desc_hobby_chs: str = betterproto.string_field(51)
    desc_hobby_chs_t: str = betterproto.string_field(52)
    desc_hobby_jp: str = betterproto.string_field(53)
    desc_hobby_en: str = betterproto.string_field(54)
    desc_hobby_kr: str = betterproto.string_field(55)
    desc_chs: str = betterproto.string_field(56)
    desc_item_chs: str = betterproto.string_field(57)
    desc_chs_t: str = betterproto.string_field(58)
    desc_item_chs_t: str = betterproto.string_field(59)
    desc_jp: str = betterproto.string_field(60)
    desc_item_jp: str = betterproto.string_field(61)
    desc_en: str = betterproto.string_field(62)
    desc_item_en: str = betterproto.string_field(63)
    desc_kr: str = betterproto.string_field(64)
    desc_item_kr: str = betterproto.string_field(65)
    collaboration: int = betterproto.uint32_field(66)
    region_limit: int = betterproto.uint32_field(67)
    skin_lib: List[int] = betterproto.uint32_field(68)
    ur: int = betterproto.uint32_field(69)
    ur_ron: int = betterproto.uint32_field(70)
    ur_liqi: int = betterproto.uint32_field(71)
    ur_cutin: str = betterproto.string_field(72)
    limited: int = betterproto.uint32_field(73)
    treasure_sp: int = betterproto.uint32_field(74)


@dataclass(eq=False, repr=False)
class ItemDefinitionView(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    res_name: str = betterproto.string_field(2)
    audio_id: int = betterproto.uint32_field(3)
    character_id: int = betterproto.uint32_field(4)
    sargs: List[str] = betterproto.string_field(5)


@dataclass(eq=False, repr=False)
class ItemDefinitionSkin(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    name_kr: str = betterproto.string_field(7)
    desc_chs: str = betterproto.string_field(8)
    desc_chs_t: str = betterproto.string_field(9)
    desc_jp: str = betterproto.string_field(10)
    desc_en: str = betterproto.string_field(11)
    desc_kr: str = betterproto.string_field(12)
    character_id: int = betterproto.uint32_field(13)
    lock_tips_chs: str = betterproto.string_field(14)
    lock_tips_chs_t: str = betterproto.string_field(15)
    lock_tips_jp: str = betterproto.string_field(16)
    lock_tips_en: str = betterproto.string_field(17)
    lock_tips_kr: str = betterproto.string_field(18)
    path: str = betterproto.string_field(19)
    exchange_item_id: int = betterproto.uint32_field(20)
    exchange_item_num: int = betterproto.int32_field(21)
    direction: int = betterproto.uint32_field(22)
    no_reverse: int = betterproto.uint32_field(23)
    lock_reverse: int = betterproto.uint32_field(24)
    offset_x: int = betterproto.int32_field(25)
    offset_y: int = betterproto.int32_field(26)
    spot_scale: str = betterproto.string_field(27)
    effective_time: str = betterproto.string_field(28)
    lobby_offset: str = betterproto.string_field(29)
    liaoshe_offset: str = betterproto.string_field(30)
    shop_offset: str = betterproto.string_field(31)
    win_offset: str = betterproto.string_field(32)
    gameend_offset: str = betterproto.string_field(33)
    starup_offset: str = betterproto.string_field(34)
    treasure_offset: str = betterproto.string_field(35)
    ck_full_0_offset: str = betterproto.string_field(36)
    ck_full_1_offset: str = betterproto.string_field(37)
    ck_full_2_offset: str = betterproto.string_field(38)
    ck_full_3_offset: str = betterproto.string_field(39)
    ck_full_single_offset: str = betterproto.string_field(40)
    ck_half_0_offset: str = betterproto.string_field(41)
    ck_half_1_offset: str = betterproto.string_field(42)
    ck_half_2_offset: str = betterproto.string_field(43)
    ck_half_3_offset: str = betterproto.string_field(44)
    ck_half_single_offset: str = betterproto.string_field(45)
    smallhead_x: int = betterproto.int32_field(46)
    smallhead_y: int = betterproto.int32_field(47)
    smallhead_width: int = betterproto.int32_field(48)
    full_x: int = betterproto.int32_field(49)
    full_y: int = betterproto.int32_field(50)
    full_width: int = betterproto.int32_field(51)
    full_height: int = betterproto.int32_field(52)
    half_x: int = betterproto.int32_field(53)
    half_y: int = betterproto.int32_field(54)
    half_width: int = betterproto.int32_field(55)
    half_height: int = betterproto.int32_field(56)
    spine_type: int = betterproto.int32_field(57)
    spine_width: int = betterproto.int32_field(58)
    spine_height: int = betterproto.int32_field(59)
    pivot_x: int = betterproto.int32_field(60)
    pivot_y: int = betterproto.int32_field(61)
    idle: int = betterproto.int32_field(62)
    greeting: int = betterproto.int32_field(63)
    celebrate: int = betterproto.int32_field(64)
    click: int = betterproto.int32_field(65)
    greeting_init: int = betterproto.int32_field(66)
    click2: int = betterproto.int32_field(67)
    celebrate_idle: int = betterproto.int32_field(68)


@dataclass(eq=False, repr=False)
class ItemDefinitionItemRecovery(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ItemDefinitionItemManualPool(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    res_id: int = betterproto.uint32_field(2)
    res_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ItemDefinitionSourceLimit(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    item_id: int = betterproto.uint32_field(2)
    item_limit: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ItemDefinitionItemPackage(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    res_id: int = betterproto.uint32_field(2)
    res_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ItemDefinitionFakeRandomPool(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    stage_count: List[int] = betterproto.uint32_field(2)
    stage_weight: List[int] = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ItemDefinitionLoadingImage(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    img_path: str = betterproto.string_field(2)
    thumb_path: str = betterproto.string_field(3)
    sort: int = betterproto.uint32_field(4)
    unlock_items: List[int] = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class ItemDefinitionFunctionItem(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    args: List[int] = betterproto.uint32_field(3)
    name: int = betterproto.uint32_field(4)
    desc_func: int = betterproto.uint32_field(5)
    desc: int = betterproto.uint32_field(6)
    icon: str = betterproto.string_field(7)
    icon_transparent: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class LeaderboardLeaderboard(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    start_time: str = betterproto.string_field(2)
    end_time: str = betterproto.string_field(3)
    refresh_cd: int = betterproto.uint32_field(4)
    max_count: int = betterproto.uint32_field(5)
    show_list: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class LevelDefinitionLevelDefinition(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.int32_field(2)
    primary_level: int = betterproto.uint32_field(3)
    secondary_level: int = betterproto.uint32_field(4)
    init_point: int = betterproto.uint32_field(5)
    end_point: int = betterproto.uint32_field(6)
    primary_icon: str = betterproto.string_field(7)
    name_chs: str = betterproto.string_field(8)
    name_chs_t: str = betterproto.string_field(9)
    name_jp: str = betterproto.string_field(10)
    name_en: str = betterproto.string_field(11)
    name_kr: str = betterproto.string_field(12)
    full_name_chs: str = betterproto.string_field(13)
    full_name_chs_t: str = betterproto.string_field(14)
    full_name_jp: str = betterproto.string_field(15)
    full_name_en: str = betterproto.string_field(16)
    full_name_kr: str = betterproto.string_field(17)
    can_degrade: int = betterproto.uint32_field(18)
    can_upgrade: int = betterproto.uint32_field(19)
    can_getpoint: int = betterproto.uint32_field(20)
    rankpt1: int = betterproto.int32_field(21)
    rankpt2: int = betterproto.int32_field(22)
    top_rank_id: int = betterproto.uint32_field(23)


@dataclass(eq=False, repr=False)
class LevelDefinitionCharacter(betterproto.Message):
    level: int = betterproto.uint32_field(1)
    character_id: int = betterproto.uint32_field(2)
    exp: int = betterproto.uint32_field(3)
    reward: str = betterproto.string_field(4)
    unlock_says: int = betterproto.uint32_field(5)
    unlock_desc_chs: str = betterproto.string_field(6)
    unlock_desc_chs_t: str = betterproto.string_field(7)
    unlock_desc_jp: str = betterproto.string_field(8)
    unlock_desc_en: str = betterproto.string_field(9)
    unlock_desc_kr: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class LevelDefinitionTrail(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    init_level: int = betterproto.uint32_field(2)
    end_level: int = betterproto.uint32_field(3)
    trail_icon: int = betterproto.uint32_field(4)
    trail_fire: int = betterproto.int32_field(5)


@dataclass(eq=False, repr=False)
class LevelDefinitionTopRank(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    rank_pt: List[int] = betterproto.int32_field(2)
    top_rank_pt: List[int] = betterproto.int32_field(3)
    mode: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class MallGoods(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    desc: str = betterproto.string_field(7)
    desc_chs: str = betterproto.string_field(8)
    desc_chs_t: str = betterproto.string_field(9)
    desc_jp: str = betterproto.string_field(10)
    desc_en: str = betterproto.string_field(11)
    desc_kr: str = betterproto.string_field(12)
    icon: str = betterproto.string_field(13)
    resource_id: int = betterproto.uint32_field(14)
    resource_count: int = betterproto.uint32_field(15)
    vip_exp: int = betterproto.uint32_field(16)
    cny: int = betterproto.uint32_field(17)
    price: str = betterproto.string_field(18)
    first_desc_chs: str = betterproto.string_field(19)
    first_desc_chs_t: str = betterproto.string_field(20)
    first_desc_jp: str = betterproto.string_field(21)
    first_desc_en: str = betterproto.string_field(22)
    first_desc_kr: str = betterproto.string_field(23)
    first_extend_add: int = betterproto.uint32_field(24)
    normal_desc_chs: str = betterproto.string_field(25)
    normal_desc_chs_t: str = betterproto.string_field(26)
    normal_desc_jp: str = betterproto.string_field(27)
    normal_desc_en: str = betterproto.string_field(28)
    normal_desc_kr: str = betterproto.string_field(29)
    normal_extend_add: int = betterproto.uint32_field(30)
    type: int = betterproto.uint32_field(31)


@dataclass(eq=False, repr=False)
class MallProduct(betterproto.Message):
    payment_platform: int = betterproto.uint32_field(1)
    goods_id: int = betterproto.uint32_field(2)
    product_type: int = betterproto.uint32_field(3)
    product_id: str = betterproto.string_field(4)
    currency_code: str = betterproto.string_field(5)
    currency_price: int = betterproto.uint32_field(6)
    actual_code: str = betterproto.string_field(7)
    actual_price: int = betterproto.uint32_field(8)
    brief_desc: str = betterproto.string_field(9)
    detail_desc: str = betterproto.string_field(10)


@dataclass(eq=False, repr=False)
class MallGoodsShelves(betterproto.Message):
    id: str = betterproto.string_field(1)
    goods_id: int = betterproto.uint32_field(2)
    currency_code: str = betterproto.string_field(3)
    currency_price: int = betterproto.uint32_field(4)
    price: str = betterproto.string_field(5)
    is_monthcard: int = betterproto.uint32_field(6)


@dataclass(eq=False, repr=False)
class MallZoneParams(betterproto.Message):
    zone_id: str = betterproto.string_field(1)
    key: str = betterproto.string_field(2)
    string_value: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MallMonthTicket(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    resource_id: int = betterproto.uint32_field(7)
    resource_count: int = betterproto.uint32_field(8)
    vip_exp: int = betterproto.uint32_field(9)
    effective_time: int = betterproto.uint32_field(10)
    icon: str = betterproto.string_field(11)
    desc_chs: str = betterproto.string_field(12)
    desc_chs_t: str = betterproto.string_field(13)
    desc_jp: str = betterproto.string_field(14)
    desc_en: str = betterproto.string_field(15)
    desc_kr: str = betterproto.string_field(16)
    desc_detail_chs: str = betterproto.string_field(17)
    desc_detail_chs_t: str = betterproto.string_field(18)
    desc_detail_jp: str = betterproto.string_field(19)
    desc_detail_en: str = betterproto.string_field(20)
    desc_detail_kr: str = betterproto.string_field(21)
    desc_detail2_chs: str = betterproto.string_field(22)
    desc_detail2_chs_t: str = betterproto.string_field(23)
    desc_detail2_jp: str = betterproto.string_field(24)
    desc_detail2_en: str = betterproto.string_field(25)
    desc_detail2_kr: str = betterproto.string_field(26)


@dataclass(eq=False, repr=False)
class MallChannelConfig(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    currency_platforms: str = betterproto.string_field(2)
    free_jade_ids: str = betterproto.string_field(3)
    paid_jade_ids: str = betterproto.string_field(4)
    free_voucher_ids: str = betterproto.string_field(5)
    paid_voucher_ids: str = betterproto.string_field(6)
    goods_id: int = betterproto.uint32_field(7)
    shelves_id: str = betterproto.string_field(8)
    name: str = betterproto.string_field(9)


@dataclass(eq=False, repr=False)
class MallMonthTicketInfo(betterproto.Message):
    id: int = betterproto.uint32_field(1)


@dataclass(eq=False, repr=False)
class MatchShilianShilian(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    ticket_id: int = betterproto.uint32_field(3)
    currency_id: int = betterproto.uint32_field(4)
    currency_count: int = betterproto.uint32_field(5)
    mode: int = betterproto.uint32_field(6)
    mode1: int = betterproto.uint32_field(7)
    mode2: int = betterproto.uint32_field(8)
    init_point: int = betterproto.int32_field(9)
    back_point: int = betterproto.int32_field(10)


@dataclass(eq=False, repr=False)
class MatchShilianShilianReward(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    reward_id: int = betterproto.uint32_field(2)
    reward_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class MatchShilianShilianTime(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    start: str = betterproto.string_field(2)
    end: str = betterproto.string_field(3)


@dataclass(eq=False, repr=False)
class MiscFunctionDailySignIn(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    reward_id: int = betterproto.uint32_field(2)
    reward_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class RankIntroduceRank(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    info: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class RankIntroduceRank3(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    info: List[str] = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SeasonSeason(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    start_time: str = betterproto.string_field(2)
    end_time: str = betterproto.string_field(3)
    disappear_time: str = betterproto.string_field(4)
    match_mode: int = betterproto.uint32_field(5)
    level_ticket_pool: int = betterproto.uint32_field(6)
    ticket_retry: int = betterproto.uint32_field(7)
    point_item_id: int = betterproto.uint32_field(8)
    point_consume: int = betterproto.uint32_field(9)
    desc_chs: str = betterproto.string_field(10)
    desc_jp: str = betterproto.string_field(11)
    desc_en: str = betterproto.string_field(12)
    desc_chs_t: str = betterproto.string_field(13)
    desktop_type: int = betterproto.uint32_field(14)


@dataclass(eq=False, repr=False)
class SeasonLevelTicket(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    level: int = betterproto.uint32_field(2)
    game_count: int = betterproto.uint32_field(3)
    weight: int = betterproto.uint32_field(4)
    task: List[int] = betterproto.uint32_field(5)
    reward: str = betterproto.string_field(6)


@dataclass(eq=False, repr=False)
class SeasonLevelTicketPool(betterproto.Message):
    pool_id: int = betterproto.uint32_field(1)
    level_lower: int = betterproto.uint32_field(2)
    level_upper: int = betterproto.uint32_field(3)
    ticket_level: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class SeasonTicketRetry(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    count: int = betterproto.uint32_field(2)
    cost: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class SeasonSeasonReward(betterproto.Message):
    season_id: int = betterproto.uint32_field(1)
    rank_lower: int = betterproto.uint32_field(2)
    rank_upper: int = betterproto.uint32_field(3)
    rewards: str = betterproto.string_field(4)


@dataclass(eq=False, repr=False)
class ShopsZhpGoods(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    icon: str = betterproto.string_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    item_id: int = betterproto.uint32_field(7)
    name_kr: str = betterproto.string_field(8)
    buy_limit: int = betterproto.int32_field(9)
    currency: int = betterproto.uint32_field(10)
    price: int = betterproto.uint32_field(11)
    need_amount: int = betterproto.uint32_field(12)
    show_has: int = betterproto.int32_field(15)


@dataclass(eq=False, repr=False)
class ShopsZhpRefreshGroup(betterproto.Message):
    pass


@dataclass(eq=False, repr=False)
class ShopsZhpRefreshPrice(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    refresh_price: int = betterproto.uint32_field(2)


@dataclass(eq=False, repr=False)
class ShopsGoods(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    category: int = betterproto.uint32_field(2)
    category_goods: int = betterproto.uint32_field(3)
    icon: str = betterproto.string_field(4)
    name_chs: str = betterproto.string_field(5)
    name_chs_t: str = betterproto.string_field(6)
    name_jp: str = betterproto.string_field(7)
    name_en: str = betterproto.string_field(8)
    name_kr: str = betterproto.string_field(9)
    desc_chs: str = betterproto.string_field(10)
    desc_chs_t: str = betterproto.string_field(11)
    desc_jp: str = betterproto.string_field(12)
    desc_en: str = betterproto.string_field(13)
    desc_kr: str = betterproto.string_field(14)
    item_id: int = betterproto.uint32_field(15)
    price: str = betterproto.string_field(16)
    need_amount: int = betterproto.uint32_field(17)
    buy_limit: int = betterproto.int32_field(18)
    show_has: int = betterproto.int32_field(19)
    sort: int = betterproto.uint32_field(20)
    discount: int = betterproto.uint32_field(21)
    sell_activity: int = betterproto.uint32_field(22)
    launch_time: str = betterproto.string_field(23)
    func: str = betterproto.string_field(24)
    discount_activity: int = betterproto.uint32_field(25)
    zone: str = betterproto.string_field(26)


@dataclass(eq=False, repr=False)
class ShopsGoodsPackage(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    good_id: int = betterproto.uint32_field(2)
    good_count: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class ShopsIntervalRefreshGoods(betterproto.Message):
    group_id: int = betterproto.uint32_field(1)
    goods_id: int = betterproto.uint32_field(2)
    interval: int = betterproto.uint32_field(3)
    interval_type: int = betterproto.uint32_field(4)


@dataclass(eq=False, repr=False)
class ShopsItemPackage(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    item_info: str = betterproto.string_field(2)


@dataclass(eq=False, repr=False)
class SpotSpot(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    unique_id: int = betterproto.uint32_field(2)
    type: int = betterproto.uint32_field(3)
    name_chs: str = betterproto.string_field(4)
    name_chs_t: str = betterproto.string_field(5)
    name_jp: str = betterproto.string_field(6)
    name_en: str = betterproto.string_field(7)
    name_kr: str = betterproto.string_field(8)
    level_limit: int = betterproto.uint32_field(9)
    is_married: int = betterproto.uint32_field(10)
    lock_tips_chs: str = betterproto.string_field(11)
    lock_tips_chs_t: str = betterproto.string_field(12)
    lock_tips_jp: str = betterproto.string_field(13)
    lock_tips_en: str = betterproto.string_field(14)
    lock_tips_kr: str = betterproto.string_field(15)
    queque: int = betterproto.uint32_field(16)
    content_chs: str = betterproto.string_field(17)
    content_chs_t: str = betterproto.string_field(18)
    content_jp: str = betterproto.string_field(19)
    content_en: str = betterproto.string_field(20)
    content_kr: str = betterproto.string_field(21)
    content_path: str = betterproto.string_field(22)
    jieju: List[int] = betterproto.uint32_field(23)


@dataclass(eq=False, repr=False)
class SpotRewards(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    content_chs: str = betterproto.string_field(3)
    content_chs_t: str = betterproto.string_field(4)
    content_jp: str = betterproto.string_field(5)
    content_en: str = betterproto.string_field(6)
    content_kr: str = betterproto.string_field(7)
    reward: str = betterproto.string_field(8)


@dataclass(eq=False, repr=False)
class SpotEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    activity_id: int = betterproto.uint32_field(2)
    key_item_id: int = betterproto.uint32_field(3)
    key_amount: int = betterproto.uint32_field(4)
    sort: int = betterproto.uint32_field(5)
    unlock_time: str = betterproto.string_field(6)
    content_path: str = betterproto.string_field(7)
    title_chs: str = betterproto.string_field(8)
    title_chs_t: str = betterproto.string_field(9)
    title_jp: str = betterproto.string_field(10)
    title_en: str = betterproto.string_field(11)
    title_kr: str = betterproto.string_field(12)
    subtitle_chs: str = betterproto.string_field(13)
    subtitle_chs_t: str = betterproto.string_field(14)
    subtitle_jp: str = betterproto.string_field(15)
    subtitle_en: str = betterproto.string_field(16)
    subtitle_kr: str = betterproto.string_field(17)
    content_chs: str = betterproto.string_field(18)
    content_chs_t: str = betterproto.string_field(19)
    content_jp: str = betterproto.string_field(20)
    content_en: str = betterproto.string_field(21)
    content_kr: str = betterproto.string_field(22)


@dataclass(eq=False, repr=False)
class SpotCharacterSpot(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    sort: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs2: str = betterproto.string_field(4)
    name_chs_t: str = betterproto.string_field(5)
    name_chs_t2: str = betterproto.string_field(6)
    name_jp: str = betterproto.string_field(7)
    name_jp2: str = betterproto.string_field(8)
    name_en: str = betterproto.string_field(9)
    name_kr: str = betterproto.string_field(10)
    open: int = betterproto.uint32_field(11)
    init_skin: int = betterproto.uint32_field(12)
    full_fetter_skin: int = betterproto.uint32_field(13)
    hand: int = betterproto.uint32_field(14)
    favorite: int = betterproto.uint32_field(15)
    star_5_material: str = betterproto.string_field(16)
    star_5_cost: int = betterproto.uint32_field(17)
    can_marry: int = betterproto.uint32_field(18)
    exchange_item_id: int = betterproto.uint32_field(19)
    exchange_item_num: int = betterproto.int32_field(20)
    emo: str = betterproto.string_field(21)
    sound: int = betterproto.uint32_field(22)
    sound_volume: float = betterproto.float_field(23)
    sex: int = betterproto.uint32_field(24)
    desc_stature_chs: str = betterproto.string_field(25)
    desc_stature_chs_t: str = betterproto.string_field(26)
    desc_stature_jp: str = betterproto.string_field(27)
    desc_stature_en: str = betterproto.string_field(28)
    desc_stature_kr: str = betterproto.string_field(29)
    desc_birth_chs: str = betterproto.string_field(30)
    desc_birth_chs_t: str = betterproto.string_field(31)
    desc_birth_jp: str = betterproto.string_field(32)
    desc_birth_en: str = betterproto.string_field(33)
    desc_birth_kr: str = betterproto.string_field(34)
    desc_age_chs: str = betterproto.string_field(35)
    desc_age_chs_t: str = betterproto.string_field(36)
    desc_age_jp: str = betterproto.string_field(37)
    desc_age_en: str = betterproto.string_field(38)
    desc_age_kr: str = betterproto.string_field(39)
    desc_bloodtype_chs: str = betterproto.string_field(40)
    desc_bloodtype_chs_t: str = betterproto.string_field(41)
    desc_bloodtype_jp: str = betterproto.string_field(42)
    desc_bloodtype_en: str = betterproto.string_field(43)
    desc_bloodtype_kr: str = betterproto.string_field(44)
    desc_cv_chs: str = betterproto.string_field(45)
    desc_cv_chs_t: str = betterproto.string_field(46)
    desc_cv_jp: str = betterproto.string_field(47)
    desc_cv_en: str = betterproto.string_field(48)
    desc_cv_kr: str = betterproto.string_field(49)
    desc_hobby_chs: str = betterproto.string_field(50)
    desc_hobby_chs_t: str = betterproto.string_field(51)
    desc_hobby_jp: str = betterproto.string_field(52)
    desc_hobby_en: str = betterproto.string_field(53)
    desc_hobby_kr: str = betterproto.string_field(54)
    desc_chs: str = betterproto.string_field(55)
    desc_item_chs: str = betterproto.string_field(56)
    desc_chs_t: str = betterproto.string_field(57)
    desc_item_chs_t: str = betterproto.string_field(58)
    desc_jp: str = betterproto.string_field(59)
    desc_item_jp: str = betterproto.string_field(60)
    desc_en: str = betterproto.string_field(61)
    desc_item_en: str = betterproto.string_field(62)
    desc_kr: str = betterproto.string_field(63)
    desc_item_kr: str = betterproto.string_field(64)
    collaboration: int = betterproto.uint32_field(65)
    skin_lib: List[int] = betterproto.uint32_field(66)
    ur: int = betterproto.uint32_field(67)
    ur_ron: int = betterproto.uint32_field(68)
    ur_liqi: int = betterproto.uint32_field(69)
    ur_cutin: str = betterproto.string_field(70)
    limited: int = betterproto.uint32_field(71)
    treasure_sp: int = betterproto.uint32_field(72)


@dataclass(eq=False, repr=False)
class SpotSkinSpot(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: int = betterproto.uint32_field(2)
    name_chs: str = betterproto.string_field(3)
    name_chs_t: str = betterproto.string_field(4)
    name_jp: str = betterproto.string_field(5)
    name_en: str = betterproto.string_field(6)
    name_kr: str = betterproto.string_field(7)
    desc_chs: str = betterproto.string_field(8)
    desc_chs_t: str = betterproto.string_field(9)
    desc_jp: str = betterproto.string_field(10)
    desc_en: str = betterproto.string_field(11)
    desc_kr: str = betterproto.string_field(12)
    character_id: int = betterproto.uint32_field(13)
    lock_tips_chs: str = betterproto.string_field(14)
    lock_tips_chs_t: str = betterproto.string_field(15)
    lock_tips_jp: str = betterproto.string_field(16)
    lock_tips_en: str = betterproto.string_field(17)
    lock_tips_kr: str = betterproto.string_field(18)
    path: str = betterproto.string_field(19)
    exchange_item_id: int = betterproto.uint32_field(20)
    exchange_item_num: int = betterproto.int32_field(21)
    direction: int = betterproto.uint32_field(22)
    no_reverse: int = betterproto.uint32_field(23)
    lock_reverse: int = betterproto.uint32_field(24)
    offset_x: int = betterproto.int32_field(25)
    offset_y: int = betterproto.int32_field(26)
    spot_scale: str = betterproto.string_field(27)
    effective_time: str = betterproto.string_field(28)
    lobby_offset: str = betterproto.string_field(29)
    liaoshe_offset: str = betterproto.string_field(30)
    shop_offset: str = betterproto.string_field(31)
    win_offset: str = betterproto.string_field(32)
    gameend_offset: str = betterproto.string_field(33)
    starup_offset: str = betterproto.string_field(34)
    treasure_offset: str = betterproto.string_field(35)
    ck_full_0_offset: str = betterproto.string_field(36)
    ck_full_1_offset: str = betterproto.string_field(37)
    ck_full_2_offset: str = betterproto.string_field(38)
    ck_full_3_offset: str = betterproto.string_field(39)
    ck_full_single_offset: str = betterproto.string_field(40)
    ck_half_0_offset: str = betterproto.string_field(41)
    ck_half_1_offset: str = betterproto.string_field(42)
    ck_half_2_offset: str = betterproto.string_field(43)
    ck_half_3_offset: str = betterproto.string_field(44)
    ck_half_single_offset: str = betterproto.string_field(45)
    smallhead_x: int = betterproto.int32_field(46)
    smallhead_y: int = betterproto.int32_field(47)
    smallhead_width: int = betterproto.int32_field(48)
    full_x: int = betterproto.int32_field(49)
    full_y: int = betterproto.int32_field(50)
    full_width: int = betterproto.int32_field(51)
    full_height: int = betterproto.int32_field(52)
    half_x: int = betterproto.int32_field(53)
    half_y: int = betterproto.int32_field(54)
    half_width: int = betterproto.int32_field(55)
    half_height: int = betterproto.int32_field(56)
    spine_type: int = betterproto.int32_field(57)
    spine_width: int = betterproto.int32_field(58)
    spine_height: int = betterproto.int32_field(59)
    pivot_x: int = betterproto.int32_field(60)
    pivot_y: int = betterproto.int32_field(61)
    idle: str = betterproto.string_field(62)
    greeting: int = betterproto.int32_field(63)
    celebrate: int = betterproto.int32_field(64)
    click: int = betterproto.int32_field(65)
    greeting_init: int = betterproto.int32_field(66)
    click2: int = betterproto.int32_field(67)
    celebrate_idle: int = betterproto.int32_field(68)


@dataclass(eq=False, repr=False)
class SpotAudioSpot(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    path: str = betterproto.string_field(2)
    time_length: float = betterproto.float_field(3)
    str: builtins.str = betterproto.string_field(4)
    type: int = betterproto.uint32_field(5)


@dataclass(eq=False, repr=False)
class StrStr(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: str = betterproto.string_field(2)
    chs: str = betterproto.string_field(3)
    chs_t: str = betterproto.string_field(4)
    jp: str = betterproto.string_field(5)
    en: str = betterproto.string_field(6)
    kr: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class StrEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    type: str = betterproto.string_field(2)
    chs: str = betterproto.string_field(3)
    chs_t: str = betterproto.string_field(4)
    jp: str = betterproto.string_field(5)
    en: str = betterproto.string_field(6)
    kr: str = betterproto.string_field(7)


@dataclass(eq=False, repr=False)
class TournamentTournaments(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name: str = betterproto.string_field(2)
    game_ticket_id: int = betterproto.uint32_field(3)


@dataclass(eq=False, repr=False)
class TutorialInit(betterproto.Message):
    episode_id: int = betterproto.uint32_field(1)
    dora: str = betterproto.string_field(2)
    rival: str = betterproto.string_field(3)
    init_score: str = betterproto.string_field(4)
    paihe: str = betterproto.string_field(5)
    chang: int = betterproto.uint32_field(6)
    ju: int = betterproto.uint32_field(7)
    benchang: int = betterproto.uint32_field(8)
    first_position: int = betterproto.uint32_field(9)
    view_position: int = betterproto.uint32_field(10)
    start_shoupai: str = betterproto.string_field(11)
    start_ming: str = betterproto.string_field(12)
    end_shoupai: str = betterproto.string_field(13)
    end_ming: str = betterproto.string_field(14)
    end_yaku: str = betterproto.string_field(15)
    ura_dora: str = betterproto.string_field(16)
    end_fu: int = betterproto.uint32_field(17)
    hu_score: int = betterproto.uint32_field(18)
    flow_score: str = betterproto.string_field(19)


@dataclass(eq=False, repr=False)
class TutorialStep(betterproto.Message):
    episode_id: int = betterproto.uint32_field(1)
    id: int = betterproto.uint32_field(2)
    seat: int = betterproto.uint32_field(3)
    act_type: int = betterproto.uint32_field(4)
    act_param: str = betterproto.string_field(5)
    tingpai_param: str = betterproto.string_field(6)
    is_zhenting: int = betterproto.uint32_field(7)
    str_type: int = betterproto.uint32_field(8)
    str_id: int = betterproto.uint32_field(9)
    view_ui_hand: int = betterproto.uint32_field(10)
    pic_path: str = betterproto.string_field(11)
    button_show: str = betterproto.string_field(12)
    button_pai: str = betterproto.string_field(13)
    player_act: int = betterproto.uint32_field(14)
    player_param: str = betterproto.string_field(15)


@dataclass(eq=False, repr=False)
class VipVip(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    img: str = betterproto.string_field(7)
    desc_chs: str = betterproto.string_field(8)
    desc_chs_t: str = betterproto.string_field(9)
    desc_jp: str = betterproto.string_field(10)
    desc_en: str = betterproto.string_field(11)
    desc_kr: str = betterproto.string_field(12)
    charge: int = betterproto.uint32_field(13)
    gift_limit: int = betterproto.uint32_field(14)
    friend_added: int = betterproto.uint32_field(15)
    shop_free_refresh: int = betterproto.uint32_field(16)
    shop_refresh_limit: int = betterproto.uint32_field(17)
    buddy_bonus: int = betterproto.uint32_field(18)
    favourite_limit: int = betterproto.uint32_field(19)
    title_id: int = betterproto.uint32_field(20)
    rewards: List[str] = betterproto.string_field(21)


@dataclass(eq=False, repr=False)
class VoiceSound(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    name_chs: str = betterproto.string_field(2)
    name_chs_t: str = betterproto.string_field(3)
    name_jp: str = betterproto.string_field(4)
    name_en: str = betterproto.string_field(5)
    name_kr: str = betterproto.string_field(6)
    words_chs: str = betterproto.string_field(7)
    words_chs_t: str = betterproto.string_field(8)
    words_jp: str = betterproto.string_field(9)
    words_en: str = betterproto.string_field(10)
    words_kr: str = betterproto.string_field(11)
    category: int = betterproto.uint32_field(12)
    type: str = betterproto.string_field(13)
    level_limit: int = betterproto.uint32_field(14)
    bond_limit: int = betterproto.uint32_field(15)
    time_length: float = betterproto.float_field(16)
    path: str = betterproto.string_field(17)
    hide: int = betterproto.uint32_field(18)
    date_limit: str = betterproto.string_field(19)


@dataclass(eq=False, repr=False)
class VoiceEvent(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    words_chs: str = betterproto.string_field(2)
    words_chs_t: str = betterproto.string_field(3)
    words_jp: str = betterproto.string_field(4)
    words_en: str = betterproto.string_field(5)
    words_kr: str = betterproto.string_field(6)
    category: int = betterproto.uint32_field(7)
    type: str = betterproto.string_field(8)
    stage: int = betterproto.uint32_field(9)
    time_length: float = betterproto.float_field(10)
    path: str = betterproto.string_field(11)
    volume_fix: float = betterproto.float_field(12)


@dataclass(eq=False, repr=False)
class VoiceSpot(betterproto.Message):
    id: int = betterproto.uint32_field(1)
    character: int = betterproto.uint32_field(2)
    type: int = betterproto.uint32_field(3)
    path: str = betterproto.string_field(4)
